import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

REPORT_DIR = "data/reports"


def ensure_report_dir():
    os.makedirs(REPORT_DIR, exist_ok=True)


def safe_filename_time():
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def write_text_report(file_path, content):
    with open(file_path, "w") as file:
        file.write(content)


def txt_report_to_pdf(txt_path):
    if not os.path.exists(txt_path):
        return None

    pdf_path = txt_path.replace(".txt", ".pdf")

    with open(txt_path, "r") as file:
        content = file.read()

    lines = content.splitlines()

    title = lines[0] if lines else "CrowdVision AI Report"

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=42,
        bottomMargin=42,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CrowdVisionTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=18,
    )

    section_style = ParagraphStyle(
        "CrowdVisionSection",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        textColor=colors.HexColor("#0369a1"),
        spaceBefore=10,
        spaceAfter=8,
    )

    normal_style = ParagraphStyle(
        "CrowdVisionNormal",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=15,
        textColor=colors.HexColor("#111827"),
    )

    story = []

    story.append(Paragraph(title, title_style))
    story.append(Paragraph("Generated by CrowdVision AI", normal_style))
    story.append(Spacer(1, 18))

    table_rows = []
    recommendation_lines = []
    in_recommendation = False

    for line in lines[1:]:
        clean_line = line.strip()

        if not clean_line:
            continue

        if clean_line == "Recommended Action:":
            in_recommendation = True
            continue

        if clean_line == "Generated By:":
            in_recommendation = False
            continue

        if in_recommendation:
            recommendation_lines.append(clean_line)
            continue

        if ":" in clean_line:
            key, value = clean_line.split(":", 1)
            table_rows.append([
                Paragraph(f"<b>{key.strip()}</b>", normal_style),
                Paragraph(value.strip(), normal_style),
            ])

    if table_rows:
        table = Table(table_rows, colWidths=[150, 330])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e0f2fe")),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#111827")),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ]))
        story.append(table)
        story.append(Spacer(1, 18))

    story.append(Paragraph("Recommended Action", section_style))

    if recommendation_lines:
        story.append(Paragraph(" ".join(recommendation_lines), normal_style))
    else:
        story.append(Paragraph("Monitor situation and continue observation.", normal_style))

    story.append(Spacer(1, 22))
    story.append(Paragraph("CrowdVision AI Safety Intelligence Report", normal_style))

    doc.build(story)

    return pdf_path


def generate_incident_report(
    camera_profile,
    total_people,
    zone_count,
    occupancy,
    density_level,
    danger_zone,
    incident_duration,
    recommendation
):
    ensure_report_dir()

    filename = f"incident_report_{safe_filename_time()}.txt"
    file_path = os.path.join(REPORT_DIR, filename)

    content = f"""
CrowdVision AI Incident Report

Report Type: Incident
Generated At: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Camera Profile: {camera_profile}
Total People: {total_people}
Zone Count: {zone_count}
Occupancy: {occupancy}
Density Level: {density_level}

Danger Zone: {danger_zone}
Incident Duration: {incident_duration} seconds

Recommended Action:
{recommendation}

Generated By:
CrowdVision AI
""".strip()

    write_text_report(file_path, content)
    txt_report_to_pdf(file_path)

    return file_path


def generate_anomaly_report(
    camera_profile,
    total_people,
    occupancy,
    anomaly_type,
    anomaly_score,
    anomaly_severity,
    anomaly_zone,
    anomaly_recommendation
):
    ensure_report_dir()

    filename = f"anomaly_report_{safe_filename_time()}.txt"
    file_path = os.path.join(REPORT_DIR, filename)

    content = f"""
CrowdVision AI Anomaly Report

Report Type: Anomaly
Generated At: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Camera Profile: {camera_profile}
Total People: {total_people}
Occupancy: {occupancy}

Anomaly Type: {anomaly_type}
Anomaly Score: {anomaly_score}%
Severity: {anomaly_severity}
Anomaly Zone: {anomaly_zone}

Recommended Action:
{anomaly_recommendation}

Generated By:
CrowdVision AI
""".strip()

    write_text_report(file_path, content)
    txt_report_to_pdf(file_path)

    return file_path


def generate_camera_health_report(
    camera_profile,
    camera_health_data,
    recommendation="Check camera source, lens, stream, lighting, cable, or network immediately."
):
    ensure_report_dir()

    filename = f"camera_health_report_{safe_filename_time()}.txt"
    file_path = os.path.join(REPORT_DIR, filename)

    camera_health_data = camera_health_data or {}

    content = f"""
CrowdVision AI Camera Integrity Report

Report Type: Camera Health / Tamper
Generated At: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Camera Profile: {camera_profile}
Status: {camera_health_data.get("status", "Unknown")}
Severity: {camera_health_data.get("severity", "Unknown")}
Tamper Detected: {camera_health_data.get("tamper_detected", False)}
Tamper Type: {camera_health_data.get("tamper_type", "None")}
Signal Quality: {camera_health_data.get("signal_quality", "Unknown")}
Brightness: {camera_health_data.get("brightness", 0)}
Blur Score: {camera_health_data.get("blur_score", 0)}
Frame Change: {camera_health_data.get("frame_change", 0)}
Frozen Seconds: {camera_health_data.get("frozen_seconds", 0)}
Message: {camera_health_data.get("message", "No message")}

Recommended Action:
{recommendation}

Generated By:
CrowdVision AI
""".strip()

    write_text_report(file_path, content)
    txt_report_to_pdf(file_path)

    return file_path